title = "Servo"
disableKinds = ["taxonomy", "taxonomyTerm"]
copyright = "The Servo Project Developers"

enableGitInfo = true

[markup.highlight]
style = "paraiso-dark"

[params]
font_awesome_version = "5.12.0"
description = "an independent, modular, embeddable web engine."
favicon = "img/servo-symbol-color-no-container.png"
repositoryUrl = "https://github.com/servo/servo.org"
contentDir = "/content/"
heroImg = "screenshot.png"

[params.logos]
navbar = "servo-color-negative-no-container.png"

[[params.colors.extra]]
name = "github-color"
hex = "#000000"

[[params.colors.extra]]
name = "twitter-color"
hex = "#00aced"

[[params.social]]
name = "Github"
color = "github-color"
url = "https://github.com/servo/servo"
icon = "fab fa-github"

[[params.social]]
name = "Twitter"
color = "twitter-color"
url = "https://twitter.com/ServoDev"
icon = "fab fa-twitter"

[[params.fonts]]
name = "Fira Sans"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Fira Mono"
sizes = [300, 400, 600, 700]
type = "monospace"

[[params.fonts]]
name = "Fire Sans"
sizes = [100, 200, 300, 400, 500, 600, 700]
type = "heading_font"

[[menu.main]]
name = "How to start"
url = "/howtostart/"
weight = 1

[[menu.main]]
name = "Contributing"
url = "/contributing/"
weight = 2

[[menu.main]]
name = "Governance"
url = "/governance/"
weight = 3

[[menu.main]]
name = "Blog"
url = "https://blog.servo.org/"
weight = 3

[[params.download]]
name = "Windows EXE"
href="nightly/windows-msvc/servo-latest.exe"

[[params.download]]
name = "Windows ZIP"
href="nightly/windows-msvc/servo-latest.zip"

[[params.download]]
name  = "UWP (arm64/x64)"
href="nightly/uwp/servo-latest.zip"
sha256="nightly/uwp/servo-latest.zip.sha256"

[[params.download]]
name  = "macOS (x64)"
href="nightly/mac/servo-latest.dmg"
sha256="nightly/mac/servo-latest.dmg.sha256"

[[params.download]]
name  = "Linux (x64)"
href="nightly/linux/servo-latest.tar.gz"
sha256="nightly/linux/servo-latest.tar.gz.sha256"
